"""empty message

Revision ID: cbb0d7d4b925
Revises: 
Create Date: 2019-03-31 11:57:50.348615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb0d7d4b925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('project_id', sa.String(length=128), nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['reviewer'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['reviewer'], ['id'])
    op.drop_column('review', 'project_id')
    # ### end Alembic commands ###
